export const GET_DOCTOR_REVIEWS = `GET_DOCTOR_REVIEWS`;
export const USER_LOGIN = `USER_LOGIN`;
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_FAIL_PASS = "USER_LOGIN_FAIL_PASS";
